/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InventoryManager;

import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class StockPanel extends javax.swing.JPanel {
        
    public StockPanel() {
        initComponents();
    }
    
    private String[] loadSupplierForItemForm() {
        String[] suppliers = Supplier.getAll_sp().keySet().toArray(String[]::new);

        // Clear existing items in the combo box before populating
//        supIdCb.removeAllItems();  // Clears the combo box for fresh data

        // Optional: Display a message if no suppliers found
        if (suppliers.length == 0) {
            System.out.println("No suppliers found.");
        } 

        return suppliers;

    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        stock_table = new javax.swing.JTable();
        stockSearchButton = new javax.swing.JButton();
        stockValueTf = new javax.swing.JTextField();
        // Populate the comboBox with column names
        String[] columns = {
            "itemID", "itemName", "description", "category",
            "unitPrice", "supplierID", "stockLevel",
            "reorderLevel", "itemEntryDate"
        };
        stockColumnCb = new javax.swing.JComboBox<>(columns);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("STOCK");
        jLabel16.setPreferredSize(new java.awt.Dimension(218, 64));

        stock_table.setModel(Item.populateTable());
        jScrollPane4.setViewportView(stock_table);

        stockSearchButton.setText("Search");
        stockSearchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockSearchButtonMouseClicked(evt);
            }
        });

        stockValueTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockValueTfActionPerformed(evt);
            }
        });

        stockColumnCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockColumnCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(stockColumnCb, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stockValueTf, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)
                            .addComponent(stockSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockSearchButton)
                    .addComponent(stockValueTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockColumnCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stockSearchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockSearchButtonMouseClicked
        // Get the selected column from the comboBox
        String selectedColumn = (String) stockColumnCb.getSelectedItem();

        // Get the value from the text field
        String filterValue = stockValueTf.getText().trim();

        // Clear previous results in the table
        DefaultTableModel model = (DefaultTableModel) stock_table.getModel();
        model.setRowCount(0);
        try {
            // Loop through each item and filter based on selected column and input value
            for (Item item : Item.getAll_item().values()) {
                Map<String, String> item_dict = item.toStrMap();
                // Check if the value in the selected column matches the filter value
                if (item_dict.get(selectedColumn) != null && item_dict.get(selectedColumn).contains(filterValue)) {
                    // Create a row for the table if the item matches the filter
                    String[] newRow = {
                        item_dict.get("itemID"),
                        item_dict.get("itemName"),
                        item_dict.get("description"),
                        item_dict.get("category"),
                        item_dict.get("unitPrice"),
                        item_dict.get("supplierID"),
                        item_dict.get("stockLevel"),
                        item_dict.get("reorderLevel"),
                        item_dict.get("itemEntryDate")
                    };

                    // Add the row to the table model
                    model.addRow(newRow);
                }
            }
        } catch (Exception ex) {
            System.err.println("Error loading items: " + ex.getMessage());
        }
    }//GEN-LAST:event_stockSearchButtonMouseClicked

    private void stockValueTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockValueTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockValueTfActionPerformed

    private void stockColumnCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockColumnCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockColumnCbActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> stockColumnCb;
    private javax.swing.JButton stockSearchButton;
    private javax.swing.JTextField stockValueTf;
    private javax.swing.JTable stock_table;
    // End of variables declaration//GEN-END:variables
}
