/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PurchaseManager;

import Admin.Profile_form;
import FinanceManager.purchaseInvoice;
import FinanceManager.purchaseInvoice_table_and_form;
import InventoryManager.Item;
import Utility.editPermission;
import InventoryManager.ItemPanel;
import InventoryManager.Supplier;
import InventoryManager.SupplierPanel;
import Login.Login;
import SalesManager.PurchaseRequisition;
import SalesManager.PurchaseRequisitionRecordsPanel;
import SalesManager.ViewItemsPanel;
import User.PurchaseManager;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author User
 */
public class PurchaseManager_PO extends javax.swing.JFrame {

    private PurchaseManager purchase;

    public PurchaseManager_PO(PurchaseManager purchase) {
        this.purchase = purchase;
        initComponents();
        // adjustTabWidth();
        setSize(1074, 750);  // Use fixed size
        refreshPage();
        
        // Add a ChangeListener for specific tabs
        PurchaseManager_UI.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                refreshPage();
            }
        });
    }
    
    private void adjustTabWidth() {
        int tabCount = PurchaseManager_UI.getTabCount();
        int paneWidth = PurchaseManager_UI.getWidth()-85;
        int tabWidth = paneWidth / tabCount;

        for (int i = 0; i < tabCount; i++) {
            PurchaseManager_UI.setTabComponentAt(i, new JLabel(PurchaseManager_UI.getTitleAt(i), SwingConstants.CENTER) {{
                setPreferredSize(new Dimension(tabWidth, getPreferredSize().height));
            }});
        }
    }    
    
    // private asm.purchaseOrder.PurchaseOrder_table_and_form purchaseOrder_panel;
    private ItemPanel itemPanel;
    private PurchaseOrder_table_and_form purchaseOrder_panel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PurchaseManager_UI = new javax.swing.JTabbedPane();
        pm_user_profile = new javax.swing.JPanel();
        pm_item = new javax.swing.JPanel();
        pm_supplier = new javax.swing.JPanel();
        pm_pr = new javax.swing.JPanel();
        pm_po = new javax.swing.JPanel();
        pm_pi = new javax.swing.JPanel();
        logout = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Manager");
        setName("PurchaseManager"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        PurchaseManager_UI.setPreferredSize(new java.awt.Dimension(1024, 650));

        pm_user_profile.setPreferredSize(new java.awt.Dimension(1024, 650));

        javax.swing.GroupLayout pm_user_profileLayout = new javax.swing.GroupLayout(pm_user_profile);
        pm_user_profile.setLayout(pm_user_profileLayout);
        pm_user_profileLayout.setHorizontalGroup(
            pm_user_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        pm_user_profileLayout.setVerticalGroup(
            pm_user_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("User Profile", pm_user_profile);
        Profile_form profile_form = new Profile_form(purchase);
        pm_user_profile.setLayout(new BorderLayout());
        pm_user_profile.add(profile_form, BorderLayout.CENTER);

        pm_user_profile.revalidate();
        pm_user_profile.repaint();

        pm_item.setPreferredSize(new java.awt.Dimension(1024, 650));

        javax.swing.GroupLayout pm_itemLayout = new javax.swing.GroupLayout(pm_item);
        pm_item.setLayout(pm_itemLayout);
        pm_itemLayout.setHorizontalGroup(
            pm_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        pm_itemLayout.setVerticalGroup(
            pm_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Item", pm_item);
        pm_item.setLayout(new BorderLayout());

        pm_supplier.setPreferredSize(new java.awt.Dimension(1024, 650));

        javax.swing.GroupLayout pm_supplierLayout = new javax.swing.GroupLayout(pm_supplier);
        pm_supplier.setLayout(pm_supplierLayout);
        pm_supplierLayout.setHorizontalGroup(
            pm_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        pm_supplierLayout.setVerticalGroup(
            pm_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Supplier", pm_supplier);

        pm_pr.setPreferredSize(new java.awt.Dimension(1024, 650));

        javax.swing.GroupLayout pm_prLayout = new javax.swing.GroupLayout(pm_pr);
        pm_pr.setLayout(pm_prLayout);
        pm_prLayout.setHorizontalGroup(
            pm_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        pm_prLayout.setVerticalGroup(
            pm_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Purchase Requisition", pm_pr);

        pm_po.setPreferredSize(new java.awt.Dimension(1024, 650));

        javax.swing.GroupLayout pm_poLayout = new javax.swing.GroupLayout(pm_po);
        pm_po.setLayout(pm_poLayout);
        pm_poLayout.setHorizontalGroup(
            pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        pm_poLayout.setVerticalGroup(
            pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Purchase Order", pm_po);
        purchaseOrder_panel = new PurchaseOrder_table_and_form(editPermission.edit, purchase.getUser_id());
        pm_po.add(purchaseOrder_panel);

        pm_po.setLayout(new BorderLayout());
        pm_po.add(purchaseOrder_panel, BorderLayout.CENTER);
        pm_po.revalidate();
        pm_po.repaint();

        javax.swing.GroupLayout pm_piLayout = new javax.swing.GroupLayout(pm_pi);
        pm_pi.setLayout(pm_piLayout);
        pm_piLayout.setHorizontalGroup(
            pm_piLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        pm_piLayout.setVerticalGroup(
            pm_piLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Purchase Invoice", pm_pi);

        logout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                logoutComponentShown(evt);
            }
        });

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Log Out", logout);

        getContentPane().add(PurchaseManager_UI);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logoutComponentShown
        // TODO add your handling code here:
        Login login = new Login();
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_logoutComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PurchaseManager purchase = new PurchaseManager();
                new PurchaseManager_PO(purchase).setVisible(true);
            }
        });
    }
    
    private void refreshPage() {
        // create an instance for each panel
        ViewItemsPanel view_Item_Panel = new ViewItemsPanel();
        SupplierPanel supplier_Panel = new SupplierPanel(editPermission.readOnly);
        PurchaseRequisitionRecordsPanel purchase_Requisition_panel = new PurchaseRequisitionRecordsPanel(editPermission.approve, "PM0001");
        PurchaseOrder_table_and_form purchase_Order_Panel = new PurchaseOrder_table_and_form(editPermission.edit, "PM0001");
        purchaseInvoice_table_and_form purchase_Invoice_Panel = new purchaseInvoice_table_and_form(editPermission.readOnly,"PM0001");
        
        // set panel to their respective tab
//        PurchaseManager_UI.setComponentAt(PurchaseManager_UI.indexOfTab("User Profile"), );
        PurchaseManager_UI.setComponentAt(PurchaseManager_UI.indexOfTab("Item"), view_Item_Panel);
        PurchaseManager_UI.setComponentAt(PurchaseManager_UI.indexOfTab("Supplier"), supplier_Panel);
        PurchaseManager_UI.setComponentAt(PurchaseManager_UI.indexOfTab("Purchase Requisition"), purchase_Requisition_panel);
        PurchaseManager_UI.setComponentAt(PurchaseManager_UI.indexOfTab("Purchase Order"), purchase_Order_Panel);
        PurchaseManager_UI.setComponentAt(PurchaseManager_UI.indexOfTab("Purchase Invoice"), purchase_Invoice_Panel);
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PurchaseManager_UI;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel pm_item;
    private javax.swing.JPanel pm_pi;
    private javax.swing.JPanel pm_po;
    private javax.swing.JPanel pm_pr;
    private javax.swing.JPanel pm_supplier;
    private javax.swing.JPanel pm_user_profile;
    // End of variables declaration//GEN-END:variables
}
