/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package asm;

import asm.utilities.editPermission;
import java.io.IOException;
import java.text.ParseException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ChangeListener;
import javax.swing.text.JTextComponent;

/**
 *
 * @author brenna
 */
public class purchaseInvoice_table_and_form extends javax.swing.JPanel {
    private editPermission permission;
    private String creator;
    private purchaseInvoice selected_pi;
    
    public purchaseInvoice_table_and_form(editPermission permission,String creator) {
        try {
            purchaseInvoice.Read();
            this.permission=permission;
            this.creator=creator;
            initComponents();
        } catch (ParseException | IOException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    private asm.purchaseInvoice_form purchaseInvoice_form;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pi_scroll_panel = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        pi_table = new javax.swing.JTable();
        BTN_pay = new javax.swing.JButton();
        BTN_arrived = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1240, 540));

        pi_table.setModel(purchaseInvoice.populateTable(editPermission.edit, creator));
        pi_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pi_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pi_table);

        jScrollPane2.setViewportView(jScrollPane1);

        BTN_pay.setText("Pay");
        BTN_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_payActionPerformed(evt);
            }
        });

        BTN_arrived.setText("Arrived");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_arrived, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pi_scroll_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pi_scroll_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_arrived, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(BTN_pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        purchaseInvoice_form = new asm.purchaseInvoice_form(pi_table, editPermission.edit, "FM0001");
        pi_scroll_panel.setViewportView(purchaseInvoice_form);
    }// </editor-fold>//GEN-END:initComponents

    private void pi_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pi_tableMouseClicked
        int row=pi_table.getSelectedRow();
        String pi_id=pi_table.getValueAt(row, pi_table.getColumn("Purchase Invoice ID").getModelIndex()).toString();
        purchaseInvoice_form.populateForm(pi_id);
    }//GEN-LAST:event_pi_tableMouseClicked

    private void BTN_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_payActionPerformed
        try {
            int row = pi_table.getSelectedRow();
            String pi_id=pi_table.getValueAt(row, pi_table.getColumn("Purchase Invoice ID").getModelIndex()).toString();
            selected_pi = purchaseInvoice.getAll_pi().get(pi_id);
            selected_pi.setPi_status("PAID");
            selected_pi.editInvoice(selected_pi.getSupplier_id(),selected_pi.getExpected_date(),null,selected_pi.getCreated_by(),selected_pi.getCreated_date(),selected_pi.getPi_status(),selected_pi.getDelivery_status());
            pi_table.setModel(purchaseInvoice.populateTable(permission, creator));
        } catch (IOException ex) {
            Logger.getLogger(purchaseInvoice_table_and_form.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BTN_payActionPerformed

    
    public static void addChangeListener(JTextComponent text,ChangeListener changeListener){
        //code
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_arrived;
    private javax.swing.JButton BTN_pay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane pi_scroll_panel;
    private javax.swing.JTable pi_table;
    // End of variables declaration//GEN-END:variables
}
