/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SalesManager;
import asm.*;
import asm.utilities.editPermission;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author isabelle
 */
public class SalesManagerPage extends javax.swing.JFrame {
    /**
     * Creates new form SalesManagerPage
     */
    public SalesManagerPage() {
        initComponents();
        // set fixed size
        setSize(1074, 750);
        refreshPage();
        
        // Add a ChangeListener for specific tabs
        salesManagerMenu.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                refreshPage();
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        salesManagerMenu = new javax.swing.JTabbedPane();
        salesManagerUserProfile = new javax.swing.JPanel();
        salesManagerItems = new javax.swing.JPanel();
        salesManagerAddSales = new javax.swing.JPanel();
        salesManagerSalesRecords = new javax.swing.JPanel();
        salesManagerSalesReport = new javax.swing.JPanel();
        salesManagerPurchaseRequisition = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        salesManagerPurchaseOrders = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salesManagerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salesManagerMenuMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout salesManagerUserProfileLayout = new javax.swing.GroupLayout(salesManagerUserProfile);
        salesManagerUserProfile.setLayout(salesManagerUserProfileLayout);
        salesManagerUserProfileLayout.setHorizontalGroup(
            salesManagerUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        salesManagerUserProfileLayout.setVerticalGroup(
            salesManagerUserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        salesManagerMenu.addTab("User Profile", salesManagerUserProfile);

        javax.swing.GroupLayout salesManagerItemsLayout = new javax.swing.GroupLayout(salesManagerItems);
        salesManagerItems.setLayout(salesManagerItemsLayout);
        salesManagerItemsLayout.setHorizontalGroup(
            salesManagerItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        salesManagerItemsLayout.setVerticalGroup(
            salesManagerItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        salesManagerMenu.addTab("Items", salesManagerItems);

        javax.swing.GroupLayout salesManagerAddSalesLayout = new javax.swing.GroupLayout(salesManagerAddSales);
        salesManagerAddSales.setLayout(salesManagerAddSalesLayout);
        salesManagerAddSalesLayout.setHorizontalGroup(
            salesManagerAddSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        salesManagerAddSalesLayout.setVerticalGroup(
            salesManagerAddSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        salesManagerMenu.addTab("Add Sales", salesManagerAddSales);

        javax.swing.GroupLayout salesManagerSalesRecordsLayout = new javax.swing.GroupLayout(salesManagerSalesRecords);
        salesManagerSalesRecords.setLayout(salesManagerSalesRecordsLayout);
        salesManagerSalesRecordsLayout.setHorizontalGroup(
            salesManagerSalesRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        salesManagerSalesRecordsLayout.setVerticalGroup(
            salesManagerSalesRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        salesManagerMenu.addTab("Sales Records", salesManagerSalesRecords);

        javax.swing.GroupLayout salesManagerSalesReportLayout = new javax.swing.GroupLayout(salesManagerSalesReport);
        salesManagerSalesReport.setLayout(salesManagerSalesReportLayout);
        salesManagerSalesReportLayout.setHorizontalGroup(
            salesManagerSalesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        salesManagerSalesReportLayout.setVerticalGroup(
            salesManagerSalesReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        salesManagerMenu.addTab("Sales Report", salesManagerSalesReport);

        javax.swing.GroupLayout salesManagerPurchaseRequisitionLayout = new javax.swing.GroupLayout(salesManagerPurchaseRequisition);
        salesManagerPurchaseRequisition.setLayout(salesManagerPurchaseRequisitionLayout);
        salesManagerPurchaseRequisitionLayout.setHorizontalGroup(
            salesManagerPurchaseRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        salesManagerPurchaseRequisitionLayout.setVerticalGroup(
            salesManagerPurchaseRequisitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        salesManagerMenu.addTab("Create Purchase Requisition", salesManagerPurchaseRequisition);
        salesManagerMenu.addTab("Purchase Requisiton Records", jTabbedPane1);
        salesManagerMenu.addTab("Purchase Orders", salesManagerPurchaseOrders);
        salesManagerMenu.addTab("Logout", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesManagerMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesManagerMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void refreshPage() {
        // create an instance for each panel
        ViewItemsPanel itemsPanel = new ViewItemsPanel();
        AddSalesPanel addSalesPanel = new AddSalesPanel("U0001");
        SalesRecordsPanel salesRecordsPanel = new SalesRecordsPanel();
        SalesReportPanel salesReportPanel = new SalesReportPanel();
        CreatePurchaseRequisitionPanel purchaseRequisitionPanel = new CreatePurchaseRequisitionPanel("U0001");
        PurchaseRequisitionRecordsPanel purchaseRequisitionRecordsPanel = new PurchaseRequisitionRecordsPanel(editPermission.readOnly);
        PurchaseOrder_table_and_form purchaseOrderPanel = new PurchaseOrder_table_and_form(editPermission.readOnly, "U0001");
        
        // set panel to their respective tab
        salesManagerMenu.setComponentAt(salesManagerMenu.indexOfTab("Items"), itemsPanel);
        salesManagerMenu.setComponentAt(salesManagerMenu.indexOfTab("Add Sales"), addSalesPanel);
        salesManagerMenu.setComponentAt(salesManagerMenu.indexOfTab("Sales Records"), salesRecordsPanel);
        salesManagerMenu.setComponentAt(salesManagerMenu.indexOfTab("Sales Report"), salesReportPanel);
        salesManagerMenu.setComponentAt(salesManagerMenu.indexOfTab("Create Purchase Requisition"), purchaseRequisitionPanel);
        salesManagerMenu.setComponentAt(salesManagerMenu.indexOfTab("Purchase Requisiton Records"), purchaseRequisitionRecordsPanel);
        salesManagerMenu.setComponentAt(salesManagerMenu.indexOfTab("Purchase Orders"), purchaseOrderPanel);
    }

    
    
    private void salesManagerMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesManagerMenuMouseReleased

    }//GEN-LAST:event_salesManagerMenuMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesManagerPage().setVisible(true);
            }
        });
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel salesManagerAddSales;
    private javax.swing.JPanel salesManagerItems;
    private javax.swing.JTabbedPane salesManagerMenu;
    private javax.swing.JTabbedPane salesManagerPurchaseOrders;
    private javax.swing.JPanel salesManagerPurchaseRequisition;
    private javax.swing.JPanel salesManagerSalesRecords;
    private javax.swing.JPanel salesManagerSalesReport;
    private javax.swing.JPanel salesManagerUserProfile;
    // End of variables declaration//GEN-END:variables
}
