/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package asm.purchaseOrder;

import java.lang.reflect.Array;

/**
 *
 * @author User
 */
public class PurchaseOrder_panel extends javax.swing.JPanel {

    /**
     * Creates new form po_form
     */
    public PurchaseOrder_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_po_id = new javax.swing.JLabel();
        TF_po_id = new javax.swing.JTextField();
        LB_pr_id = new javax.swing.JLabel();
        TF_pr_id = new javax.swing.JTextField();
        LB_sup_id = new javax.swing.JLabel();
        TF_sup_id = new javax.swing.JTextField();
        LB_order_date = new javax.swing.JLabel();
        LB_delivery_date = new javax.swing.JLabel();
        LB_po_status = new javax.swing.JLabel();
        LB_payment_status = new javax.swing.JLabel();
        LB_approved = new javax.swing.JLabel();
        TF_approved = new javax.swing.JTextField();
        LB_approval_date = new javax.swing.JLabel();
        CB_order_status = new javax.swing.JComboBox<>();
        CB_payment_status = new javax.swing.JComboBox<>();
        DC_delivery_date = new com.toedter.calendar.JDateChooser();
        DC_order_date = new com.toedter.calendar.JDateChooser();
        DC_approval_date = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(400, 300));

        LB_po_id.setText("Purchase Order ID: ");

        TF_po_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_po_idActionPerformed(evt);
            }
        });

        LB_pr_id.setText("Purchase Requisition ID: ");

        TF_pr_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_pr_idActionPerformed(evt);
            }
        });

        LB_sup_id.setText("Supplier ID: ");

        TF_sup_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_sup_idActionPerformed(evt);
            }
        });

        LB_order_date.setText("Order Date:");

        LB_delivery_date.setText("Delivery Date");

        LB_po_status.setText("Purchase Order Status: ");

        LB_payment_status.setText("Payment Status:");

        LB_approved.setText("Approved By:");

        TF_approved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_approvedActionPerformed(evt);
            }
        });

        LB_approval_date.setText("Approval Date:");

        CB_order_status.setModel(new javax.swing.DefaultComboBoxModel<>(purchaseOrder.getPo_stat_enum()));
        CB_order_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_order_statusActionPerformed(evt);
            }
        });

        CB_payment_status.setModel(new javax.swing.DefaultComboBoxModel<>(purchaseOrder.getPayment_stat_enum()));
        CB_payment_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_payment_statusActionPerformed(evt);
            }
        });

        DC_delivery_date.setDateFormatString("dd-MMM-yyyy");

        DC_order_date.setDateFormatString("dd-MMM-yyyy");

        DC_approval_date.setDateFormatString("dd-MMM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_delivery_date)
                    .addComponent(LB_po_id)
                    .addComponent(LB_po_status)
                    .addComponent(LB_pr_id)
                    .addComponent(LB_payment_status)
                    .addComponent(LB_sup_id)
                    .addComponent(LB_approved)
                    .addComponent(LB_order_date)
                    .addComponent(LB_approval_date))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CB_payment_status, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_po_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(DC_delivery_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DC_order_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TF_pr_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(DC_approval_date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TF_sup_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TF_approved, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(CB_order_status, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_po_id)
                    .addComponent(TF_po_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_pr_id)
                    .addComponent(TF_pr_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_sup_id)
                    .addComponent(TF_sup_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_order_date)
                    .addComponent(DC_order_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_delivery_date)
                    .addComponent(DC_delivery_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_po_status)
                    .addComponent(CB_order_status, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_payment_status)
                    .addComponent(CB_payment_status, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LB_approved)
                    .addComponent(TF_approved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_approval_date)
                    .addComponent(DC_approval_date, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TF_po_id.setEditable(false);
        TF_pr_id.setEditable(false);
    }// </editor-fold>//GEN-END:initComponents

    private void TF_po_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_po_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_po_idActionPerformed

    private void TF_pr_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_pr_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_pr_idActionPerformed

    private void TF_sup_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_sup_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_sup_idActionPerformed

    private void TF_approvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_approvedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_approvedActionPerformed

    private void CB_order_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_order_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_order_statusActionPerformed

    private void CB_payment_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_payment_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_payment_statusActionPerformed

    public void populateForm(String po_id){
        purchaseOrder selected_po = purchaseOrder.getAll_po().get(po_id);
        TF_po_id.setText(selected_po.getPo_id());
        TF_pr_id.setText(selected_po.getPr_id());
        TF_sup_id.setText(selected_po.getSupplier_id());
        DC_order_date.setDate(selected_po.getOrder_date().getTime());
        
        if(selected_po.getDelivery_date() != null){
            DC_delivery_date.setDate(selected_po.getDelivery_date().getTime());
        }
        
        CB_order_status.setSelectedItem(selected_po.getPo_status());
        CB_payment_status.setSelectedItem(selected_po.getPayment_status());
        
        if(selected_po.getApproved_by() != null){
            TF_approved.setText(selected_po.getApproved_by());
        }
        
        if(selected_po.getApproval_date() != null){
            DC_approval_date.setDate(selected_po.getApproval_date().getTime());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_order_status;
    private javax.swing.JComboBox<String> CB_payment_status;
    private com.toedter.calendar.JDateChooser DC_approval_date;
    private com.toedter.calendar.JDateChooser DC_delivery_date;
    private com.toedter.calendar.JDateChooser DC_order_date;
    private javax.swing.JLabel LB_approval_date;
    private javax.swing.JLabel LB_approved;
    private javax.swing.JLabel LB_delivery_date;
    private javax.swing.JLabel LB_order_date;
    private javax.swing.JLabel LB_payment_status;
    private javax.swing.JLabel LB_po_id;
    private javax.swing.JLabel LB_po_status;
    private javax.swing.JLabel LB_pr_id;
    private javax.swing.JLabel LB_sup_id;
    private javax.swing.JTextField TF_approved;
    private javax.swing.JTextField TF_po_id;
    private javax.swing.JTextField TF_pr_id;
    private javax.swing.JTextField TF_sup_id;
    // End of variables declaration//GEN-END:variables
}
