/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asm.purchaseOrder;

import asm.purchaseOrder.PurchaseOrder_panel;
import asm.purchaseOrder.purchaseOrder;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.lang.System.Logger;
import java.text.ParseException;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class PurchaseManager_PO extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseManager_PO
     */
    public PurchaseManager_PO() {
        try {
            purchaseOrder.Read();
            initComponents();
            adjustTabWidth();

        } catch (ParseException | IOException ex) {
            System.out.print(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PurchaseManager_UI = new javax.swing.JTabbedPane();
        pm_UserProfile = new javax.swing.JPanel();
        pm_ItemSupplier = new javax.swing.JPanel();
        pm_pr = new javax.swing.JPanel();
        pm_po = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        po_table = new javax.swing.JTable(populateTable());
        scroll_po_panel = new javax.swing.JScrollPane();
        purchaseOrder_panel1 = new asm.purchaseOrder.PurchaseOrder_panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Manager");
        setName("PurchaseManager"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 640));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        PurchaseManager_UI.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        PurchaseManager_UI.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        pm_UserProfile.setPreferredSize(new java.awt.Dimension(1024, 640));

        javax.swing.GroupLayout pm_UserProfileLayout = new javax.swing.GroupLayout(pm_UserProfile);
        pm_UserProfile.setLayout(pm_UserProfileLayout);
        pm_UserProfileLayout.setHorizontalGroup(
            pm_UserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7762, Short.MAX_VALUE)
        );
        pm_UserProfileLayout.setVerticalGroup(
            pm_UserProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("User Profile", pm_UserProfile);

        javax.swing.GroupLayout pm_ItemSupplierLayout = new javax.swing.GroupLayout(pm_ItemSupplier);
        pm_ItemSupplier.setLayout(pm_ItemSupplierLayout);
        pm_ItemSupplierLayout.setHorizontalGroup(
            pm_ItemSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7762, Short.MAX_VALUE)
        );
        pm_ItemSupplierLayout.setVerticalGroup(
            pm_ItemSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Item & Supplier", pm_ItemSupplier);

        javax.swing.GroupLayout pm_prLayout = new javax.swing.GroupLayout(pm_pr);
        pm_pr.setLayout(pm_prLayout);
        pm_prLayout.setHorizontalGroup(
            pm_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7762, Short.MAX_VALUE)
        );
        pm_prLayout.setVerticalGroup(
            pm_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Purchase Requisition", pm_pr);

        pm_po.setMaximumSize(new java.awt.Dimension(1024, 560));
        pm_po.setPreferredSize(new java.awt.Dimension(1024, 560));

        po_table.setModel(populateTable());
        po_table.setPreferredSize(new java.awt.Dimension(500, 250));
        po_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        po_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        po_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                po_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(po_table);

        scroll_po_panel.setViewportView(purchaseOrder_panel1);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");

        javax.swing.GroupLayout pm_poLayout = new javax.swing.GroupLayout(pm_po);
        pm_po.setLayout(pm_poLayout);
        pm_poLayout.setHorizontalGroup(
            pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pm_poLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_po_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pm_poLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(6812, Short.MAX_VALUE))
        );
        pm_poLayout.setVerticalGroup(
            pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pm_poLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pm_poLayout.createSequentialGroup()
                        .addGroup(pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scroll_po_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        PurchaseManager_UI.addTab("Purchase Order", pm_po);

        getContentPane().add(PurchaseManager_UI);
        PurchaseManager_UI.getAccessibleContext().setAccessibleName("");
        JLabel lab = new JLabel("hi");
        lab.setPreferredSize(new Dimension(200, 30));

        PurchaseManager_UI.setTabComponentAt(0, lab);  // tab index, jLabel

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void po_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_po_tableMouseClicked
        int row = po_table.getSelectedRow();
        String po_id = po_table.getValueAt(row, po_table.getColumn("Purchase Order ID").getModelIndex()).toString();
        // JOptionPane.showMessageDialog(null, po_id); // get the value of a row and column.
        purchaseOrder_panel1.populateForm(po_id);
    }//GEN-LAST:event_po_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseManager_PO().setVisible(true);
            }
        });
    }
    
    public static ImageIcon resize(ImageIcon icon, int width, int height){
        BufferedImage img = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) img.createGraphics();
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(icon.getImage(), 0, 0, width, height, null);
        g2d.dispose();
        return new ImageIcon(img);
    }
    
    private void adjustTabWidth() {
        int tabCount = PurchaseManager_UI.getTabCount();
        int paneWidth = PurchaseManager_UI.getWidth()-85;
        int tabWidth = paneWidth / tabCount;

        for (int i = 0; i < tabCount; i++) {
            PurchaseManager_UI.setTabComponentAt(i, new JLabel(PurchaseManager_UI.getTitleAt(i), SwingConstants.CENTER) {{
                setPreferredSize(new Dimension(tabWidth, getPreferredSize().height));
            }});
        }
    }
    
    public static TableModel populateTable() {
        DefaultTableModel model = new DefaultTableModel(
            new Object[] { "Purchase Order ID", "Purchase Requisition ID", "Order Date", "Status"}, 0
        ){
            @Override
        public boolean isCellEditable(int row, int column) {
           //all cells false
           return false;
        }
        };

        // Debugging: Check if getAll_po() returns any records
        Map<String, purchaseOrder> allPurchaseOrders = purchaseOrder.getAll_po();
        System.out.println("Number of purchase orders: " + allPurchaseOrders.size());

        for (purchaseOrder po : allPurchaseOrders.values()) {

            model.addRow(new Object[] { 
                po.getPo_id(), 
                po.getPr_id(), 
                po.getOrder_date_str(), 
                po.getPo_status()
            });
        }

        return model;
    }

    public static PurchaseOrder_panel addPoPanel(){
        PurchaseOrder_panel panel = new PurchaseOrder_panel();
        return panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PurchaseManager_UI;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pm_ItemSupplier;
    private javax.swing.JPanel pm_UserProfile;
    private javax.swing.JPanel pm_po;
    private javax.swing.JPanel pm_pr;
    private javax.swing.JTable po_table;
    private asm.purchaseOrder.PurchaseOrder_panel purchaseOrder_panel1;
    private javax.swing.JScrollPane scroll_po_panel;
    // End of variables declaration//GEN-END:variables
}
