package Login;

import Admin.AdminPage;
import FinanceManager.FinanceManager_PI;
import FinanceManager.purchaseInvoice;
import InventoryManager.InventoryManagerMain;
import InventoryManager.Item;
import InventoryManager.Supplier;
import PurchaseManager.PurchaseManager_PO;
import PurchaseManager.purchaseOrder;
import SalesManager.PurchaseRequisition;
import SalesManager.Sale;
import SalesManager.SalesManagerPage;
import User.*;
import User.PurchaseManager;
import Utility.txt;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Predicate;
import javax.swing.JOptionPane;


/**
 *
 * @author tanwa
 */
public class Login extends javax.swing.JFrame {

    private final String file = "src/User/User.dat";
    
    /**
     * Creates new form Register
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userID_tbx = new javax.swing.JTextField();
        login_btn = new javax.swing.JButton();
        showPW_cb = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        password_tbx = new javax.swing.JPasswordField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setSize(new java.awt.Dimension(500, 400));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Welcome to POTS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("user id: ");

        userID_tbx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        login_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        showPW_cb.setBackground(new java.awt.Color(255, 255, 255));
        showPW_cb.setText("show password");
        showPW_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPW_cbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("password:");

        password_tbx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showPW_cb)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userID_tbx, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_tbx, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userID_tbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_tbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPW_cb)
                .addGap(35, 35, 35)
                .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void openAdminPage(Admin admin){
        AdminPage adminPage = new AdminPage(admin);  // Instantiate AdminProfile
        adminPage.setVisible(true);  // Then show the AdminProfile
    }
    
    private void openPurchasePage(PurchaseManager purchase){
        PurchaseManager_PO purchasePage = new PurchaseManager_PO(purchase); 
        purchasePage.setVisible(true);
    }
    
    private void openFinancePage(FinanceManager finance){
        FinanceManager_PI financePage = new FinanceManager_PI(finance); 
        financePage.setVisible(true);
    }
    
    private void openSalesPage(SalesManager sale){
        SalesManagerPage salesPage = new SalesManagerPage(sale); 
        salesPage.setVisible(true);
    }
    
    private void openInventoryPage(InventoryManager inventory){
        InventoryManagerMain inventoryPage = new InventoryManagerMain(inventory); 
        inventoryPage.setVisible(true);
    }
    
    
    public boolean validatedUser(Users user) {
        if (user == null || user.getUser_id() == null) {
            return false; // Early exit if user or user_id is null
        }
        return user.getUser_id().equals(userID_tbx.getText()) && user.getPassword().equals(password_tbx.getText());
    }
    
    
    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling cod here:;
        boolean success = false;
        if(userID_tbx.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out username");
            return;
        }
        else if (password_tbx.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill out the password");
            return;
        }
        
        String prefix = userID_tbx.getText().substring(0, 2); // Extract the prefix (first two characters)

        
        // Read user data from the .DAT file
        List<Object> objects = txt.ReadFromDAT(file);
        // Loop through each object and add data to the table model
        for (Object object : objects) {
            if (object instanceof Users user) {
                if (validatedUser(user)) {
                    success = true;
                    Sale.Read();
                    Supplier.Read();
                    Item.Read();
                    PurchaseRequisition.Read();
                    purchaseOrder.Read();
                    purchaseInvoice.Read();
                    // Check the actual type of the user object
                    switch (prefix) {
                        case "AD" -> {
                            if (user instanceof Admin admin) {
                                openAdminPage(admin);
                            }
                        }
                        case "PM" -> {
                            if (user instanceof PurchaseManager purchaseManager) {
                                openPurchasePage(purchaseManager);
                            } 
                        }
                        case "FM" -> {
                            if (user instanceof FinanceManager financeManager) {
                                openFinancePage(financeManager);
                            }
                        }
                        case "IM" -> {
                            if (user instanceof InventoryManager inventoryManager) {
                                openInventoryPage(inventoryManager);
                            }
                        }
                        case "SM" -> {
                            if (user instanceof SalesManager salesManager) {
                                openSalesPage(salesManager);
                            }
                        }
                        default -> {
                            success = false; // Invalid prefix
                        }
                    }

                    break; // Exit the loop once the user is processed
                }
            }
        }
        
        
        if (!success) {
        JOptionPane.showMessageDialog(null, "Login failed. Invalid credentials.");
        }
        else{
            this.setVisible(false);
        }

        
      
    }//GEN-LAST:event_login_btnActionPerformed

    private void showPW_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPW_cbActionPerformed
        // TODO add your handling code here:
        if(showPW_cb.isSelected()){
            password_tbx.setEchoChar((char)0);
        }
        else{
            password_tbx.setEchoChar('*');
        }
    }//GEN-LAST:event_showPW_cbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField password_tbx;
    private javax.swing.JCheckBox showPW_cb;
    private javax.swing.JTextField userID_tbx;
    // End of variables declaration//GEN-END:variables
}
