package javaassignment;

import javaassignment.itemAddTabForm;

public class InventoryManager extends javax.swing.JFrame {

    /**
     * Creates new form InventoryManager
     */
    public InventoryManager() {
        initComponents();
        setTitle("Main Menu");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemTab = new javax.swing.JMenu();
        itemAddTab = new javax.swing.JMenu();
        itemEditTab = new javax.swing.JMenu();
        itemDeleteTab = new javax.swing.JMenu();
        itemViewTab = new javax.swing.JMenu();
        supTab = new javax.swing.JMenu();
        supAddTab = new javax.swing.JMenu();
        supEditTab = new javax.swing.JMenu();
        supDeleteTab = new javax.swing.JMenu();
        supViewTab = new javax.swing.JMenu();
        stockTab = new javax.swing.JMenu();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemTab.setText("Item");

        itemAddTab.setText("Add");
        itemAddTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                itemAddTabStateChanged(evt);
            }
        });
        itemAddTab.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                itemAddTabMenuSelected(evt);
            }
        });
        itemAddTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddTabMouseClicked(evt);
            }
        });
        itemAddTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddTabActionPerformed(evt);
            }
        });
        itemAddTab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemAddTabKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemAddTabKeyReleased(evt);
            }
        });
        itemTab.add(itemAddTab);

        itemEditTab.setText("Edit");
        itemEditTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemEditTabMouseClicked(evt);
            }
        });
        itemTab.add(itemEditTab);

        itemDeleteTab.setText("Delete");
        itemTab.add(itemDeleteTab);

        itemViewTab.setText("View");
        itemTab.add(itemViewTab);

        jMenuBar1.add(itemTab);

        supTab.setText("Supplier");

        supAddTab.setText("Add");
        supTab.add(supAddTab);

        supEditTab.setText("Edit");
        supTab.add(supEditTab);

        supDeleteTab.setText("Delete");
        supTab.add(supDeleteTab);

        supViewTab.setText("View");
        supTab.add(supViewTab);

        jMenuBar1.add(supTab);

        stockTab.setText("Stock");
        jMenuBar1.add(stockTab);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAddTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddTabActionPerformed
        
    }//GEN-LAST:event_itemAddTabActionPerformed
    
    
    private void itemAddTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_itemAddTabStateChanged
    }//GEN-LAST:event_itemAddTabStateChanged

    private void itemAddTabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemAddTabKeyPressed
      
    }//GEN-LAST:event_itemAddTabKeyPressed

    private void itemAddTabKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemAddTabKeyReleased
        
    }//GEN-LAST:event_itemAddTabKeyReleased

    private void itemAddTabMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_itemAddTabMenuSelected
        
    }//GEN-LAST:event_itemAddTabMenuSelected

    private void itemAddTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddTabMouseClicked
        new itemAddTabForm().setVisible(true);
    }//GEN-LAST:event_itemAddTabMouseClicked

    private void itemEditTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemEditTabMouseClicked
        new itemEditTabForm().setVisible(true);
    }//GEN-LAST:event_itemEditTabMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryManager().setVisible(true);
            }
        });
    }

       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu itemAddTab;
    public javax.swing.JMenu itemDeleteTab;
    public javax.swing.JMenu itemEditTab;
    public javax.swing.JMenu itemTab;
    public javax.swing.JMenu itemViewTab;
    public javax.swing.JMenuBar jMenuBar1;
    public java.awt.Menu menu1;
    public java.awt.Menu menu2;
    public java.awt.Menu menu3;
    public java.awt.Menu menu4;
    public java.awt.MenuBar menuBar1;
    public java.awt.MenuBar menuBar2;
    public javax.swing.JMenu stockTab;
    public javax.swing.JMenu supAddTab;
    public javax.swing.JMenu supDeleteTab;
    public javax.swing.JMenu supEditTab;
    public javax.swing.JMenu supTab;
    public javax.swing.JMenu supViewTab;
    // End of variables declaration//GEN-END:variables
}
