/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaassignment;

/**
 *
 * @author Lucius
 */
public class itemEditTabForm extends javax.swing.JFrame {

    /**
     * Creates new form itemEditTabForm
     */
    public itemEditTabForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAddTab = new javax.swing.JMenu();
        itemEditTab = new javax.swing.JMenu();
        itemDeleteTab = new javax.swing.JMenu();
        itemViewTab = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        supAddTab = new javax.swing.JMenu();
        supEditTab = new javax.swing.JMenu();
        supDeleteTab = new javax.swing.JMenu();
        supViewTab = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Item");

        jLabel1.setText("EDIT");

        jMenu1.setText("Item");

        itemAddTab.setText("Add");
        itemAddTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddTabMouseClicked(evt);
            }
        });
        jMenu1.add(itemAddTab);

        itemEditTab.setText("Edit");
        jMenu1.add(itemEditTab);

        itemDeleteTab.setText("Delete");
        jMenu1.add(itemDeleteTab);

        itemViewTab.setText("View");
        jMenu1.add(itemViewTab);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Supplier");

        supAddTab.setText("Add");
        jMenu2.add(supAddTab);

        supEditTab.setText("Edit");
        jMenu2.add(supEditTab);

        supDeleteTab.setText("Delete");
        jMenu2.add(supDeleteTab);

        supViewTab.setText("View");
        jMenu2.add(supViewTab);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Stock");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAddTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddTabMouseClicked
        new itemAddTabForm().setVisible(true);
    }//GEN-LAST:event_itemAddTabMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itemEditTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itemEditTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itemEditTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itemEditTabForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itemEditTabForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu itemAddTab;
    public javax.swing.JMenu itemDeleteTab;
    public javax.swing.JMenu itemEditTab;
    public javax.swing.JMenu itemViewTab;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu supAddTab;
    public javax.swing.JMenu supDeleteTab;
    public javax.swing.JMenu supEditTab;
    public javax.swing.JMenu supViewTab;
    // End of variables declaration//GEN-END:variables
}
