/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asm;

import asm.utilities.editPermission;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author User
 */
public class PurchaseManager_PO extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseManager_PO
     */
    public PurchaseManager_PO() {
        initComponents();
        // adjustTabWidth();
        setSize(1024, 650);  // Use fixed size
    }
    
    private void adjustTabWidth() {
        int tabCount = PurchaseManager_UI.getTabCount();
        int paneWidth = PurchaseManager_UI.getWidth()-85;
        int tabWidth = paneWidth / tabCount;

        for (int i = 0; i < tabCount; i++) {
            PurchaseManager_UI.setTabComponentAt(i, new JLabel(PurchaseManager_UI.getTitleAt(i), SwingConstants.CENTER) {{
                setPreferredSize(new Dimension(tabWidth, getPreferredSize().height));
            }});
        }
    }    
    
    // private asm.purchaseOrder.PurchaseOrder_table_and_form purchaseOrder_panel;
    private asm.PurchaseOrder_table_and_form purchaseOrder_panel;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PurchaseManager_UI = new javax.swing.JTabbedPane();
        pm_user_profile = new javax.swing.JPanel();
        pm_item = new javax.swing.JPanel();
        pm_supplier = new javax.swing.JPanel();
        pm_pr = new javax.swing.JPanel();
        pm_po = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Manager");
        setName("PurchaseManager"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        PurchaseManager_UI.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout pm_user_profileLayout = new javax.swing.GroupLayout(pm_user_profile);
        pm_user_profile.setLayout(pm_user_profileLayout);
        pm_user_profileLayout.setHorizontalGroup(
            pm_user_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        pm_user_profileLayout.setVerticalGroup(
            pm_user_profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("User Profile", pm_user_profile);

        javax.swing.GroupLayout pm_itemLayout = new javax.swing.GroupLayout(pm_item);
        pm_item.setLayout(pm_itemLayout);
        pm_itemLayout.setHorizontalGroup(
            pm_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        pm_itemLayout.setVerticalGroup(
            pm_itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Item", pm_item);

        javax.swing.GroupLayout pm_supplierLayout = new javax.swing.GroupLayout(pm_supplier);
        pm_supplier.setLayout(pm_supplierLayout);
        pm_supplierLayout.setHorizontalGroup(
            pm_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        pm_supplierLayout.setVerticalGroup(
            pm_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Supplier", pm_supplier);

        javax.swing.GroupLayout pm_prLayout = new javax.swing.GroupLayout(pm_pr);
        pm_pr.setLayout(pm_prLayout);
        pm_prLayout.setHorizontalGroup(
            pm_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        pm_prLayout.setVerticalGroup(
            pm_prLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Purchase Requisition", pm_pr);

        javax.swing.GroupLayout pm_poLayout = new javax.swing.GroupLayout(pm_po);
        pm_po.setLayout(pm_poLayout);
        pm_poLayout.setHorizontalGroup(
            pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 886, Short.MAX_VALUE)
        );
        pm_poLayout.setVerticalGroup(
            pm_poLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        PurchaseManager_UI.addTab("Purchase Order", pm_po);
        purchaseOrder_panel = new asm.PurchaseOrder_table_and_form(editPermission.edit, "PM0001");
        pm_po.add(purchaseOrder_panel);

        pm_po.setLayout(new BorderLayout());
        pm_po.add(purchaseOrder_panel, BorderLayout.CENTER);
        pm_po.revalidate();
        pm_po.repaint();

        getContentPane().add(PurchaseManager_UI);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseManager_PO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseManager_PO().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PurchaseManager_UI;
    private javax.swing.JPanel pm_item;
    private javax.swing.JPanel pm_po;
    private javax.swing.JPanel pm_pr;
    private javax.swing.JPanel pm_supplier;
    private javax.swing.JPanel pm_user_profile;
    // End of variables declaration//GEN-END:variables
}
